# Generated by Django 2.2.28 on 2026-03-24 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='no_of_ratings',
            field=models.IntegerField(default=0),
        ),
    ]
