# Generated by Django 2.2.28 on 2026-03-24 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_movie_no_of_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='rating',
            name='review',
            field=models.CharField(default='None', max_length=500),
        ),
    ]
