# Generated by Django 2.2.28 on 2026-03-25 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0003_auto_20260324_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='follow_list',
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='movie_app.UserProfile')),
                ('follows_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follows', to='movie_app.UserProfile')),
            ],
        ),
    ]
